### ISSUE TITLE
sometimes does not get past loading screen

### ISSUE THREAD

**Issue by kylemcdonald** [kylemcdonald/ExhaustingACrowd#1]
i can't track this down.. it might just be that i'm on a slow connection. maybe indicating the loading status on the first screen (if it's possible).

**Comment by HalfdanJ** [comment]
Chrome?

**Comment by kylemcdonald** [comment]
yes, chrome 41.02. sorry for the delay :)

**Comment by HalfdanJ** [comment]
I think i've solved it. Wrong loading order
