### ISSUE TITLE
fix time formatting

### ISSUE THREAD

**Issue by kylemcdonald** [kylemcdonald/ExhaustingACrowd#16]
time should be:

- 3:00 PM (correct)
- 10:00 PM (correct)
- 11:59 (correct)
- 12:00 AM (currently shows 0:00)
- 12:30 AM (currently shows 0:30)
- 1:00 AM

**Comment by HalfdanJ** [comment]
The date should also update to May 18th

**Comment by kylemcdonald** [comment]
actually, i'm going to remove the date. it's already mentioned in the credits and doesn't add much.
