### ISSUE TITLE
remove any old notes

### ISSUE THREAD

**Issue by kylemcdonald** [kylemcdonald/ExhaustingACrowd#24]
there's still a bunch at the beginning. i'll figure this out, i need to know how to manually edit the database in case i need to censor offensive stuff anyway.

**Comment by HalfdanJ** [comment]
I use postico (a mac app).
fre. 29. maj 2015 kl. 16.05 skrev Kyle McDonald <notifications@github.com>:

**Comment by kylemcdonald** [comment]
i just switched the db, but will use postico :)

**Comment by kylemcdonald** [comment]
postico was good for exporting csv from the db, but i needed to install psql and manually add the rows. i also had to manually update the IDs by offsetting the old one by 200 then running this command `\COPY public.notes FROM '/Users/kyle/Desktop/notes-purple.csv' CSV HEADER DELIMITER ','` if you know how to generate ids automatically let me know :) (or maybe i should have just removed the column from the csv?)
