### ISSUE TITLE
some notes are not removed

### ISSUE THREAD

**Issue by kylemcdonald** [kylemcdonald/ExhaustingACrowd#29]
i couldn't quite recreate this behavior, but i have two notes stuck on my screen right now:

- "taking a picture"
- "••pffft••"

i looked through the console at all the "remove" calls and none of them contained these two.

it might have had something to do with rewinding at just the right time and causing the remove never to get called?

**Comment by kylemcdonald** [comment]
this might also have something to do with being in the 'bermuda triangle' zone of 2:27pm - 3:00pm where everything starts acting really weird.

**Comment by kylemcdonald** [comment]
if i leave the tab running in the background for some time, this seems to be happening consistently.

**Comment by moonmilk** [comment]
I see it happen quite often after adding a note

**Comment by tchoi8** [comment]
im gonna exhaust the 'bermuda triangle' zone of 2:27pm - 3:00p
