### ISSUE TITLE
12mm lens link broken

### ISSUE THREAD

**Issue by eyaler** [kylemcdonald/ExhaustingACrowd#36]
the link for the 12mm lens is not available:
http://peauproductions.com/store/index.php?main_page=product_info&products_id=690

could you specify the model name or link to a similar product?

**Comment by kylemcdonald** [comment]
the invoice says: 12.00mm f/2.8 30d HFOV 5MP GP12028 (No Distortion) (GP12028)  = $85.00

i don't see the same lens on their site anymore but there are lots of others https://www.peauproductions.com/collections/gopro-hero-3-3-silver-lenses
