### ISSUE TITLE
Wondering how to implement 3D

### ISSUE THREAD

**Issue by kkshmz** [kylemcdonald/ExhaustingACrowd#37]
Hi, I was thinking of hacking this system together so that I would be able to comment in a 3D space, with video footage taken by a RICOH.
Given that clicking, automatically makes a comment, I wonder if this app would be suitable for 3D and if you guys actually tried to do so.
Thanks in advance,
Kye

**Comment by kylemcdonald** [comment]
we haven't tried that, but it sounds cool! i'm going to close this issue because it's not really a bug :)
