### ISSUE TITLE
broken in chrome & safari

### ISSUE THREAD

**Issue by kylemcdonald** [kylemcdonald/ExhaustingACrowd#38]
works in firefox.

the iframe embed says "an error occurred" but visiting the link directly works:  https://www.youtube.com/embed/?autoplay=1&controls=0&disablekb=1&enablejsapi=1&fs=0&modestbranding=1&origin=http%3A%2F%2Fwww.exhaustingacrowd.com&rel=0&showinfo=0&list=PLscUku2aaZnFE-7wKovrbi76b26VKxIT-&listType=playlist&start=0&widgetid=1

**Comment by outofambit** [comment]
is this the autoplay issue? or something else? just want to know if i should close it :)
